### ISSUE TITLE
Translation Roadmap

### ISSUE THREAD

**Issue by StanFromIreland** [python/python-docs-pl#50]
Please prioritize translating the following resources. These were selected based on popularity in the English Documentation and will be very helpful to many people once translated. 

### Resources
- [ ] [library/stdtypes](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--stdtypes/) ([published](https://docs.python.org/pl/3/library/stdtypes.html))
- [ ] [using/windows](https://app.transifex.com/python-doc/python-newest/translate/#pl/using--windows/) ([published](https://docs.python.org/pl/3/using/windows.html))
- [ ] [library/turtle](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--turtle/) ([published](https://docs.python.org/pl/3/library/turtle.html))
- [ ] [library/re](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--re/) ([published](https://docs.python.org/pl/3/library/re.html))
- [ ] [library/datetime](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--datetime/) ([published](https://docs.python.org/pl/3/library/datetime.html))
- [ ] [library/venv](http://transifex.com/python-doc/python-newest/translate/#pl/library--venv/) ([published](https://docs.python.org/pl/3/library/venv.html))
- [ ] [library/tkinter](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--tkinter/) ([published](https://docs.python.org/pl/3/library/tkinter.html))
- [ ] [library/typing](https://app.transifex.com/python-doc/python-newest/translate/#pl/library--typing/) ([published](https://docs.python.org/pl/3/library/typing.html))

**Comment by m-aciek** [comment]
Second set of resources to prioritize would be those that have already traffic under [`/pl/` filtering](https://plausible.io/docs.python.org/pages?filters=((contains,page,(/pl/)))), but are not completed in translation. Some examples:
* `installing/index`
* `library/array`
* `extending/extending`

**Comment by ONKARBH** [comment]
Hi @m-aciek , I'd like to work on this issue. Could you please assign it to me?

**Comment by StanFromIreland** [comment]
@ONKARBH Instructions for joining the translation team are in the README.
